apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpulse
  namespace: cloudpulse
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Esta anotação captura tudo o que vier depois de /api e joga para o backend
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: cloudpulse.local
    http:
      paths:
      # O REGEX (/|$)(.*) captura o que vier depois de /api
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cloudpulse-core-api
            port:
              number: 5223
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudpulse-frontend
            port:
              number: 80
