apiVersion: 1

contactPoints:
  - orgId: 1
    name: cloudpulse-default
    receivers:
      - uid: cloudpulse-default-receiver
        type: email
        disableResolveMessage: false
        settings:
          addresses: ops@cloudpulse.local
          singleEmail: false

policies:
  - orgId: 1
    receiver: cloudpulse-default
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
