apiVersion: 1
datasources:
  - name: Prometheus
    uid: cloudpulse-prometheus
    type: prometheus
    access: proxy
    url: http://cloudpulse-prometheus-tf:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: cloudpulse-loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
