apiVersion: 1
datasources:
  - name: Prometheus
    uid: cloudpulse-prometheus
    type: prometheus
    access: proxy
    url: http://cloudpulse-prometheus-tf:9090
    isDefault: true
    editable: false
