apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpulse-frontend
  namespace: cloudpulse
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: cloudpulse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudpulse-frontend
                port:
                  number: 80
