apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: cloudpulse
spec:
  type: ExternalName
  externalName: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpulse
  namespace: cloudpulse
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    # Garante o encaminhamento correto mesmo para backends externos
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
spec:
  ingressClassName: nginx
  rules:
  - host: cloudpulse.local
    http:
      paths:
      # Rota para o Backend API
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cloudpulse-core-api
            port:
              number: 5223
      # Rota para o Grafana (via Service ExternalName)
      - path: /grafana(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: grafana-external
            port:
              number: 80
      # Rota para o Frontend (Catch-all)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudpulse-frontend
            port:
              number: 80
